spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB:warehouse}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379

  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: ${NEO4J_USER:neo4j}
      password: ${NEO4J_PASSWORD:password1234}

server:
  port: 8080