# ============================================================
# Build one self-contained seed file.
#
# Everyone's database drifted apart because each person set it
# up by hand. This produces a single file that rebuilds the
# whole demo dataset from scratch, so every machine matches.
#
# Usage - just run it:
#   powershell -ExecutionPolicy Bypass -File .\tools\build_seed.ps1
#
# Output:
#   src/main/resources/db/seed/laro_seed.sql
#
# The warehouse map (V02) is machine generated from the map JSON,
# so it is copied verbatim instead of being retyped.
#
# ASCII only on purpose: Windows PowerShell 5.1 reads .ps1 using
# the system code page, so non-ASCII characters break parsing.
# ============================================================

$ErrorActionPreference = "Stop"

$seedDir = Join-Path $PSScriptRoot "..\src\main\resources\db\seed"
$seedDir = [System.IO.Path]::GetFullPath($seedDir)
$outputPath = Join-Path $seedDir "laro_seed.sql"

# Dependency order. Same order the application uses.
#   V01 users / robot spec      -> needed by everything
#   V06 product catalog         -> needed before inventory
#   V02 warehouse map + robots  -> needed by inventory
#   V05 inventory + scenarios
#   V07 box model               -> needs inventory rows
#   V08 three level racks       -> needs inventory rows
#   V09 drop expiry columns
$parts = @(
    "V01_base.sql",
    "V06_product_catalog.sql",
    "V02_warehouse_1.sql",
    "V05_inventory.sql",
    "V07_box_storage_model.sql",
    "V08_three_level_rack_storage.sql",
    "V09_remove_expiry.sql"
)

$header = @"
-- ============================================================================
-- LARO single seed file
--
-- Generated by tools/build_seed.ps1 - do not edit by hand.
-- Rebuild it after changing any db/seed/V*.sql file.
--
-- What it does
--   admin account, 60 products, warehouse 1 map (268 nodes / 356 edges),
--   10 charging stations, 48 racks, 6 robots, inventory, scenario presets
--
-- How to load (empty database, tables already created by Hibernate)
--   docker exec -i laro-be-centered-v13-27-postgres psql -U postgres -d warehouse < laro_seed.sql
--
-- Safe to run more than once. Every statement is ON CONFLICT aware.
-- ============================================================================

"@

$builder = New-Object System.Text.StringBuilder
[void]$builder.Append($header)

foreach ($part in $parts) {
    $path = Join-Path $seedDir $part
    if (-not (Test-Path -LiteralPath $path)) {
        throw "Missing seed part: $path"
    }

    [void]$builder.AppendLine("")
    [void]$builder.AppendLine("-- ==========================================================================")
    [void]$builder.AppendLine("-- from $part")
    [void]$builder.AppendLine("-- ==========================================================================")
    [void]$builder.AppendLine([System.IO.File]::ReadAllText($path, [System.Text.Encoding]::UTF8))

    Write-Host ("  + {0}" -f $part)
}

# ------------------------------------------------------------
# Fixes that belong to the combined file only.
#
# 1. robot.status
#    V02 writes 'AVAILABLE' but RobotAvailabilityStatusConverter
#    reads and writes 'IDLE' / 'BUSY'. Leaving the seed value as
#    is makes every simulation fail with NO_AVAILABLE_ROBOTS,
#    because the lookup query filters on 'IDLE'.
#
# 2. three level inventory
#    V05 fills level 1 of ten racks only, so uploaded maps and the
#    demo warehouse look different. Fill all three levels of the
#    first half of the racks instead.
# ------------------------------------------------------------
$tail = @"

-- ==========================================================================
-- combined-file fixes
-- ==========================================================================

-- 1. Robot status must match RobotAvailabilityStatusConverter.
--    The old CHECK constraint only allows AVAILABLE / UNAVAILABLE,
--    so it has to go before the values can be corrected.
ALTER TABLE robot DROP CONSTRAINT IF EXISTS robot_status_check;

UPDATE robot
   SET status = CASE status
                  WHEN 'AVAILABLE'   THEN 'IDLE'
                  WHEN 'UNAVAILABLE' THEN 'BUSY'
                  ELSE status
                END
 WHERE status IN ('AVAILABLE', 'UNAVAILABLE');

ALTER TABLE robot
  ADD CONSTRAINT robot_status_check
  CHECK (status IN ('IDLE', 'BUSY', 'CHARGING'));

-- 2. Stock all three levels of the first half of the racks so the
--    demo warehouse renders the same way an imported map does.
INSERT INTO warehouse_items (
    warehouse_id, storage_location_id, node_id, product_id,
    rack_level, received_at, quantity, inbound_quantity, outbound_quantity
)
SELECT
    ranked.warehouse_id,
    ranked.storage_location_id,
    ranked.node_id,
    ((ranked.rn - 1) * 3 + level.rack_level - 1)
        % (SELECT COUNT(*) FROM product) + 1,
    level.rack_level,
    NOW(),
    50,
    0,
    0
FROM (
    SELECT storage_location_id, warehouse_id, node_id,
           ROW_NUMBER() OVER (PARTITION BY warehouse_id
                              ORDER BY storage_location_id) AS rn,
           COUNT(*) OVER (PARTITION BY warehouse_id) AS total
    FROM storage_location
) ranked
CROSS JOIN (VALUES (1), (2), (3)) AS level(rack_level)
WHERE ranked.rn <= GREATEST(ranked.total / 2, 1)
ON CONFLICT DO NOTHING;

SELECT setval(pg_get_serial_sequence('warehouse_items', 'warehouse_item_id'),
              GREATEST((SELECT COALESCE(MAX(warehouse_item_id), 1)
                        FROM warehouse_items), 1), true);
"@

[void]$builder.Append($tail)

[System.IO.File]::WriteAllText(
    $outputPath,
    $builder.ToString(),
    (New-Object System.Text.UTF8Encoding($false))
)

$lineCount = ([System.IO.File]::ReadAllLines($outputPath)).Length

Write-Host ""
Write-Host "Done: $outputPath" -ForegroundColor Green
Write-Host ("  {0} parts, {1} lines" -f $parts.Count, $lineCount)
Write-Host ""
Write-Host "Load it into a fresh database:" -ForegroundColor DarkGray
Write-Host "  docker exec -i laro-be-centered-v13-27-postgres psql -U postgres -d warehouse < `"$outputPath`"" -ForegroundColor DarkGray
